[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0db7697cf56d30e968ae3e311da0a05b713e7949"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "2ad76254dee16add73aa02445e389cc3bf921566738a412b971b2fe1a94f4187"
    url = "https://github.com/pabloferz/LAMMPS_jll.jl/releases/download/v2020.3.3+1/LAMMPS.v2020.3.3.aarch64-linux-gnu-cxx11.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af662deaed1395a58a1af57a55a03c75df6e0b13"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "2fd80c0864149a89157dcf01eeb7b3d42f6407202d9626dab8c4e60e939e9f00"
    url = "https://github.com/pabloferz/LAMMPS_jll.jl/releases/download/v2020.3.3+1/LAMMPS.v2020.3.3.aarch64-linux-gnu-cxx03.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc021f7859bfa1e1e9db6f9215f7ff9e07963f73"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "49609b9845fa34f4d2ff5189469816c469ecfdea69e20ea4c43d08d4703e2927"
    url = "https://github.com/pabloferz/LAMMPS_jll.jl/releases/download/v2020.3.3+1/LAMMPS.v2020.3.3.x86_64-linux-gnu-cxx11.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2429169b52c6a364ea0a683cab7b2c1daec3df88"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "7b5304ea0861e98be2f888bfa866b31b73b3e67a07e2657d9a9e8d56923f4e44"
    url = "https://github.com/pabloferz/LAMMPS_jll.jl/releases/download/v2020.3.3+1/LAMMPS.v2020.3.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0f47759294adb93af61ac8f2e85be9b92f26c42f"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "b46c5ae67190f6a80d3a8b66b69aeceb2af7e5b028a9b638fa7beff5c21c62fa"
    url = "https://github.com/pabloferz/LAMMPS_jll.jl/releases/download/v2020.3.3+1/LAMMPS.v2020.3.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a43f7d6f2d7698e3e881b5c3aed1d71ac7853d5a"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "afbb142a8e81e97ddf9b8a040fc5a87f12b18a89987d3602373f23bcee7f543e"
    url = "https://github.com/pabloferz/LAMMPS_jll.jl/releases/download/v2020.3.3+1/LAMMPS.v2020.3.3.x86_64-linux-gnu-cxx03.tar.gz"
