[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "506786dc7367a6a5dfbb8303f6689fa3b13d5f7a"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "a8f13811ac40e094de98d5c554dd1956f658372366d068c282d97e9a0865dfc9"
    url = "https://github.com/pabloferz/LAMMPS_jll.jl/releases/download/v2020.3.3+0/LAMMPS.v2020.3.3.aarch64-linux-gnu-cxx11.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4d167e8e24f98c8fdd0b72e8122723fa0c5ea064"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "8bb5e44717fda1b729b576a8f2c123255400d1a16e170404ed4ecee918b1e754"
    url = "https://github.com/pabloferz/LAMMPS_jll.jl/releases/download/v2020.3.3+0/LAMMPS.v2020.3.3.aarch64-linux-gnu-cxx03.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5fa5281fde2447fcbf1f1c162342c93e3a00bd9e"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "2bb22e9a135bf72b0d503982a02b4033edf7c0d46c87e4ee2bc4ed77ced87241"
    url = "https://github.com/pabloferz/LAMMPS_jll.jl/releases/download/v2020.3.3+0/LAMMPS.v2020.3.3.x86_64-linux-gnu-cxx11.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b069b2ff85f5d39d183876f7983faad8ae0e2412"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "064b04c74684c24292f15e2c761c5dec0e612c451cf10fcbee33181a230da255"
    url = "https://github.com/pabloferz/LAMMPS_jll.jl/releases/download/v2020.3.3+0/LAMMPS.v2020.3.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a1da06066ce4d80510f9a2c652996b8bd1a40269"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "066a4623d9ebd25fc0b05c53dc1eb7478f77f9b72c0a155c717ec691ff9c0b18"
    url = "https://github.com/pabloferz/LAMMPS_jll.jl/releases/download/v2020.3.3+0/LAMMPS.v2020.3.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b21dc4cf0ddbcbfa0695f0347e33fdf8397adcf"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ea0e822039e1c99ab08301fdfc5eeb717f5f57f1b88f11557e359b91a5d7da3c"
    url = "https://github.com/pabloferz/LAMMPS_jll.jl/releases/download/v2020.3.3+0/LAMMPS.v2020.3.3.x86_64-linux-gnu-cxx03.tar.gz"
