# Autogenerated wrapper script for LAMMPS_jll for x86_64-linux-gnu-cxx03
export liblammps, lammps

using CompilerSupportLibraries_jll
using FFMPEG_jll
using FFTW_jll
using MPICH_jll
using OpenBLAS_jll
using Zlib_jll
using libpng_jll
## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "LD_LIBRARY_PATH"

# Relative path to `liblammps`
const liblammps_splitpath = ["lib", "liblammps.so"]

# This will be filled out by __init__() for all products, as it must be done at runtime
liblammps_path = ""

# liblammps-specific global declaration
# This will be filled out by __init__()
liblammps_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const liblammps = "liblammps.so.0"


# Relative path to `lammps`
const lammps_splitpath = ["bin", "lmp"]

# This will be filled out by __init__() for all products, as it must be done at runtime
lammps_path = ""

# lammps-specific global declaration
function lammps(f::Function; adjust_PATH::Bool = true, adjust_LIBPATH::Bool = true)
    global PATH, LIBPATH
    env_mapping = Dict{String,String}()
    if adjust_PATH
        if !isempty(get(ENV, "PATH", ""))
            env_mapping["PATH"] = string(PATH, ':', ENV["PATH"])
        else
            env_mapping["PATH"] = PATH
        end
    end
    if adjust_LIBPATH
        if !isempty(get(ENV, LIBPATH_env, ""))
            env_mapping[LIBPATH_env] = string(LIBPATH, ':', ENV[LIBPATH_env])
        else
            env_mapping[LIBPATH_env] = LIBPATH
        end
    end
    withenv(env_mapping...) do
        f(lammps_path)
    end
end


"""
Open all libraries
"""
function __init__()
    global artifact_dir = abspath(artifact"LAMMPS")

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    # We first need to add to LIBPATH_list the libraries provided by Julia
    append!(LIBPATH_list, [joinpath(Sys.BINDIR, Base.LIBDIR, "julia"), joinpath(Sys.BINDIR, Base.LIBDIR)])
    # From the list of our dependencies, generate a tuple of all the PATH and LIBPATH lists,
    # then append them to our own.
    foreach(p -> append!(PATH_list, p), (CompilerSupportLibraries_jll.PATH_list, FFMPEG_jll.PATH_list, FFTW_jll.PATH_list, MPICH_jll.PATH_list, OpenBLAS_jll.PATH_list, Zlib_jll.PATH_list, libpng_jll.PATH_list,))
    foreach(p -> append!(LIBPATH_list, p), (CompilerSupportLibraries_jll.LIBPATH_list, FFMPEG_jll.LIBPATH_list, FFTW_jll.LIBPATH_list, MPICH_jll.LIBPATH_list, OpenBLAS_jll.LIBPATH_list, Zlib_jll.LIBPATH_list, libpng_jll.LIBPATH_list,))

    global liblammps_path = normpath(joinpath(artifact_dir, liblammps_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global liblammps_handle = dlopen(liblammps_path)
    push!(LIBPATH_list, dirname(liblammps_path))

    global lammps_path = normpath(joinpath(artifact_dir, lammps_splitpath...))

    push!(PATH_list, dirname(lammps_path))
    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ':')
    global LIBPATH = join(LIBPATH_list, ':')

    # Add each element of LIBPATH to our DL_LOAD_PATH (necessary on platforms
    # that don't honor our "already opened" trick)
    #for lp in LIBPATH_list
    #    push!(DL_LOAD_PATH, lp)
    #end
end  # __init__()

